# Generated by Django 4.2.23 on 2025-08-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_doctor_alter_appointment_doctor_and_more'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
