# Generated by Django 4.2.23 on 2025-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
