# Generated by Django 4.2.23 on 2025-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment_doctor_prescription_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spo2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='temp',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
