# Generated by Django 4.2.23 on 2025-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctor_first_name_doctor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
