# Generated by Django 4.2.23 on 2025-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='titlw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
