# Generated by Django 4.2.23 on 2025-08-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_prescription_titlw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='titlw',
            new_name='title',
        ),
    ]
