# Generated by Django 4.2.23 on 2025-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_appointment_doctor_alter_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timings',
            field=models.CharField(blank=True, help_text='e.g. Before meal, After meal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(help_text='e.g. 5 days, 1 month', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(help_text='e.g. 1-0-1, Twice a day', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, help_text='Additional instructions', null=True),
        ),
    ]
